"""DNS inside a lease: the container's resolver is unreachable from the namespace.

Observed live 2026-09-17: inside a leased namespace `curl` failed every hostname
with `curl: (6) Could not resolve host` (and `getent`/`socket.gethostbyname`
too), because `/etc/resolv.conf` was copied verbatim from the container and
points at `127.0.0.11` - Docker's embedded resolver, which lives on the
CONTAINER's loopback. In a child namespace `127.0.0.11` is that namespace's own
loopback, so nothing answers. httpx/katana were unaffected only because they
carry their own resolver list; the replay sender (`curl` inside the lease) is not
so lucky.
"""
from __future__ import annotations

import socket
import threading
import time

from kali.http_history.dns import DnsForwarder, lease_resolv_conf

DOCKER_RESOLV = """# Generated by Docker Engine.
# This file can be edited; Docker Engine will not make further changes once it
# has been modified.

nameserver 127.0.0.11
search homenet.example.it tail59928d.ts.net
options edns0 trust-ad ndots:0
"""


def test_lease_resolv_conf_replaces_the_unreachable_docker_resolver():
    text = lease_resolv_conf(DOCKER_RESOLV, "172.30.0.1")
    lines = [line for line in text.splitlines() if line.strip()]
    assert lines[0] == "nameserver 172.30.0.1"
    assert "127.0.0.11" not in text, "the container loopback resolver cannot answer in a child namespace"
    # search/options survive: they are the container's naming policy, not an address.
    assert any(line.startswith("search ") for line in lines)
    assert any(line.startswith("options ") for line in lines)


def test_lease_resolv_conf_keeps_reachable_nameservers_as_fallback():
    parent = "nameserver 127.0.0.11\nnameserver 9.9.9.9\nnameserver 0.0.0.0\n"
    text = lease_resolv_conf(parent, "172.30.0.5")
    nameservers = [line.split()[1] for line in text.splitlines() if line.startswith("nameserver")]
    assert nameservers == ["172.30.0.5", "9.9.9.9"]


def test_lease_resolv_conf_works_with_an_empty_parent():
    text = lease_resolv_conf("", "172.30.0.1")
    assert text.strip() == "nameserver 172.30.0.1"


def _upstream(reply: bytes) -> tuple[socket.socket, int, list[bytes]]:
    """A fake resolver: one datagram in, a fixed datagram out."""
    sock = socket.socket(socket.AF_INET, socket.SOCK_DGRAM)
    sock.bind(("127.0.0.1", 0))
    seen: list[bytes] = []

    def serve() -> None:
        data, peer = sock.recvfrom(4096)
        seen.append(data)
        sock.sendto(reply, peer)

    threading.Thread(target=serve, daemon=True).start()
    return sock, sock.getsockname()[1], seen


def test_forwarder_relays_a_query_to_the_container_resolver():
    """The lease talks to its gateway; the gateway forwards to Docker's resolver."""
    reply = b"\x124fake-answer"
    upstream_sock, upstream_port, seen = _upstream(reply)
    forwarder = DnsForwarder(upstream_host="127.0.0.1", upstream_port=upstream_port)
    try:
        port = forwarder.bind("127.0.0.1", port=0)
        client = socket.socket(socket.AF_INET, socket.SOCK_DGRAM)
        client.settimeout(5.0)
        client.sendto(b"\x00\x01question", ("127.0.0.1", port))
        data, _peer = client.recvfrom(4096)
        assert data == reply
        assert seen == [b"\x00\x01question"], "the query must reach the upstream unchanged"
    finally:
        forwarder.stop()
        upstream_sock.close()


def test_forwarder_is_idempotent_per_address_and_survives_an_upstream_outage():
    forwarder = DnsForwarder(upstream_host="127.0.0.1", upstream_port=1)  # nothing listens on :1
    try:
        port = forwarder.bind("127.0.0.1", port=0)
        assert forwarder.bind("127.0.0.1", port=port) == port, "bind must be idempotent"
        client = socket.socket(socket.AF_INET, socket.SOCK_DGRAM)
        client.settimeout(0.4)
        client.sendto(b"\x00\x02q", ("127.0.0.1", port))
        try:
            client.recvfrom(4096)
            raise AssertionError("an unreachable upstream must not fabricate a reply")
        except socket.timeout:
            pass
        # The listener must stay alive: a broken upstream degrades that query,
        # never the resolver.
        time.sleep(0.05)
        assert forwarder.is_alive("127.0.0.1")
        assert forwarder.unbind("127.0.0.1") is True
        assert forwarder.is_alive("127.0.0.1") is False
    finally:
        forwarder.stop()
